services:
  web:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
  db:
    image: container-registry.oracle.com/mysql/community-server:8.0
    ports:
      - "3306:3306"
  

